export * from './currency';
export * from './paymentMethod';
export * from './secrets.js';
export declare const config: {
    readonly jwtSecret: string;
    readonly jwtRefreshSecret: string;
    jwtExpiresIn: string;
    jwtRefreshExpiresIn: string;
    port: number;
    readonly databaseUrl: string;
    frontendUrl: string;
    telegramBotToken: string;
    telegramWebhookUrl: string;
    telegramWebhookSecret: string;
    uploadDir: string;
    s3Endpoint: string;
    s3Region: string;
    s3AccessKey: string;
    s3SecretKey: string;
    s3Bucket: string;
    s3ForcePathStyle: boolean;
};
